### ISSUE TITLE
Error "Accessing static property DoubleClick::$enqueued as non static"

### ISSUE THREAD

**Issue by samueldjack** [INN/doubleclick-for-wp#37]
We're using the DoubleClick for Wordpress plugin on the same site as the WPLR Sync plugin.

When we invoke the WPLR sync plugin it exposes an error in the DoubleClick-for-Wordpress plugin:

The error is `Accessing static property DoubleClick::$enqueued as non static` it occurs in this code [here](https://github.com/INN/DoubleClick-for-WordPress/blob/79800f706f983f7097fd64a51f7eef6b858fd8d3/dfw-init.php#L94).

I think the fix is to change the line in question to `if(!self::$enqueued) {`.

There's also an identical error two lines below.

**Comment by benlk** [comment]
Hi Samuel,

Thanks for your bug report. Can you answer these questions for me, please?

- Is the WPLR Sync plugin you're using [WP/LR Sync](https://meowapps.com/wplr-sync/) for syncing Lightroom with WordPress?
- Are you running with `WP_DEBUG` set to true?
- What version of PHP are you using?
- What version of WordPress are you using?
- Is this problem fixed by using the 37-static-properties branch of this plugin? https://github.com/INN/DoubleClick-for-WordPress/tree/37-static-properties

**Comment by samueldjack** [comment]
Hi Ben,

Sorry for not getting back to you sooner. To answer your questions:

1.  Yes, that's the one
2. No, WP_DEBUG is false
3. PHP 7.1
4. Wordpress 4.7
5. I'll have a look to see if that new version helps.

Thanks!

**Comment by izzygld** [comment]
i have the same error
after deactivating all other plugins still get this error!

```Notice: Accessing static property DoubleClick::$enqueued as non static in /var/www/vhosts/local.jewishaction.com/public/content/plugins/doubleclick-for-wp/dfw-init.php on line 96```

**Comment by rclations** [comment]
Hey @izzygld & @samueldjack thanks for the reports here. We've got some updates coming out soon that should resolve these issues. Stay tuned
